---
title: "Overzicht practicum 1"
author: "Ludger Goeminne"
date: "10/10/2018"
output: html_document
---

# 1. Voor het begin van het eerste practicum

Tijdens de practica zullen we gebruik maken van het statistisch softwarepakket R, in combinatie met RStudio. Het is aangeraden dat jullie jullie eigen laptop meebrengen naar het practicum, waarop jullie reeds R en RStudio geïnstalleerd hebben. Aangezien we snel van start zullen gaan, raden we jullie ook aan om jezelf al eens oppervlakkig vertrouwd te maken met RStudio en R Markdown.

## 1.1. R en RStudio installeren

Op deze pagina wordt uitgelegd hoe je R en RStudio moet installeren:

https://statomics.github.io/statistiekBasisCursus/assets/practica/practicum1/RStudio_installeren.html

## 1.2. Introductie tot RStudio en R Markdown

Het is aangeraden om reeds vertrouwd te zijn met RStudio en R Markdown alvorens jullie het eerste practicum meevolgen. Tijdens het practicum zullen wij namelijk steeds met R Markdown-bestanden werken, dit is een bestandstype dat zowel tekst als computercode kan integreren in één bestand, en het jullie makkelijk zal maken om de practica te studeren. Hiervoor hebben wij een tutorial voorbereid. Deze tutorial kan je hier vinden:

https://statomics.github.io/statistiekBasisCursus/assets/practica/practicum1/rmarkdownVoorbeeld.Rmd

Dit bestand is een .Rmd-bestand. Je kan dit openen in RStudio, en het bestand zou vanzelfsprekend moeten zijn om te volgen. Het bestand kan door RStudio gecompileerd worden tot een HTML-pagina, en de resulterende HTML-pagina vinden jullie hier:

https://statomics.github.io/statistiekBasisCursus/assets/practica/practicum1/rmarkdownVoorbeeld.html

Zo zie je gemakkelijk de correspondentie tussen de broncode en het gecompileerde bestand.

Degenen die nog dieper willen ingaan in het vertrouwd raken met R, kunnen ook volgende tutorials doorlopen:

 - datacamp 'Introduction to R' (hoofdstukken 1 t.e.m. 3): https://campus.datacamp.com/courses/free-introduction-to-r/
 - swirl tutorial binnen R: https://swirlstats.com/students.html. Hiermee kan je binnen R of RStudio de programmeercode aanleren.
